version: ‘3.7’
services:
  nginx:
    image: nginx
    ports:
      - "5000:5000"
    depends_on:
      - php
    volumes:
      - "$PWD/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "$PWD/html:/usr/share/nginx/html"
    container_name: "compose-nginx"
  php:
    build: ./php
    image: php:fpm
    ports:
      - "9000:9000"
    volumes:
      - "$PWD/html:/var/www/html"
    container_name: "compose-php"
networks:
  app_net:
    driver: bridge
